version: "3.8"
services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ads_db
      MYSQL_USER: ads_user
      MYSQL_PASSWORD: adspass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root 
      PMA_PASSWORD: rootpass
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=sqlite
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  mariadb_data:
  n8n_data:
